export const records = [
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "IrvWellnessPC", Status: "Warning", Product_Version: "8.1.1.170", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "TustRehabADC", Status: "Failed", Product_Version: "8.1.1.170", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "AnaHealthPC", Status: "Warning", Product_Version: "7.9.6.155", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "TustRehabADC", Status: "Success", Product_Version: "8.1.1.170", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "TustinCarePC", Status: "Warning", Product_Version: "8.0.0.162", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Prime Medical Center Fullerton", Computer_Name: "FullPrimePC", Status: "Success", Product_Version: "7.8.4.140", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "AnaHealthPC", Status: "Warning", Product_Version: "8.0.0.162", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "TustinCarePC", Status: "Failed", Product_Version: "7.9.6.155", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "IrvWellnessPC", Status: "Warning", Product_Version: "7.9.6.155", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "FullPrimePC", Status: "Failed", Product_Version: "7.9.5.150", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "FullPrimePC", Status: "Failed", Product_Version: "8.1.1.170", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Prime Medical Center Fullerton", Computer_Name: "TustRehabADC", Status: "Failed", Product_Version: "7.9.6.155", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "TustinCarePC", Status: "Failed", Product_Version: "7.8.4.140", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "TustRehabADC", Status: "Success", Product_Version: "7.8.4.140", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "AnaHealthPC", Status: "Failed", Product_Version: "7.8.4.140", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "TustRehabADC", Status: "Success", Product_Version: "7.9.5.150", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "TustinCarePC", Status: "Success", Product_Version: "8.0.0.162", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "TustinCarePC", Status: "Warning", Product_Version: "8.0.0.162", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "IrvWellnessPC", Status: "Success", Product_Version: "8.0.0.162", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "IrvWellnessPC", Status: "Failed", Product_Version: "7.9.6.155", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Prime Medical Center Fullerton", Computer_Name: "AnaHealthPC", Status: "Warning", Product_Version: "7.9.6.155", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "FullPrimePC", Status: "Success", Product_Version: "8.1.1.170", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "AnaHealthPC", Status: "Warning", Product_Version: "7.8.4.140", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "FullPrimePC", Status: "Warning", Product_Version: "8.0.0.162", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "TustRehabADC", Status: "Success", Product_Version: "8.1.1.170", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Prime Medical Center Fullerton", Computer_Name: "TustRehabADC", Status: "Failed", Product_Version: "7.9.6.155", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "AnaHealthPC", Status: "Failed", Product_Version: "8.0.0.162", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "FullPrimePC", Status: "Warning", Product_Version: "7.9.5.150", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "IrvWellnessPC", Status: "Failed", Product_Version: "7.9.6.155", Space_Used: "500GB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "AnaHealthPC", Status: "Success", Product_Version: "7.8.4.140", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Prime Medical Center Fullerton", Computer_Name: "FullPrimePC", Status: "Failed", Product_Version: "8.0.0.162", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "AnaHealthPC", Status: "Failed", Product_Version: "8.1.1.170", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "IrvWellnessPC", Status: "Success", Product_Version: "7.9.6.155", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "FullPrimePC", Status: "Failed", Product_Version: "7.9.5.150", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "FullPrimePC", Status: "Success", Product_Version: "7.9.6.155", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Prime Medical Center Fullerton", Computer_Name: "AnaHealthPC", Status: "Warning", Product_Version: "7.8.4.140", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "TustinCarePC", Status: "Failed", Product_Version: "8.0.0.162", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "AnaHealthPC", Status: "Failed", Product_Version: "7.9.5.150", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "FullPrimePC", Status: "Warning", Product_Version: "8.1.1.170", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "HealthCare Partners Anaheim", Computer_Name: "TustinCarePC", Status: "Success", Product_Version: "8.1.1.170", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Prime Medical Center Fullerton", Computer_Name: "AnaHealthPC", Status: "Failed", Product_Version: "7.9.5.150", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "IrvWellnessPC", Status: "Success", Product_Version: "8.0.0.162", Space_Used: "3TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "AnaHealthPC", Status: "Failed", Product_Version: "8.1.1.170", Space_Used: "1.5TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Wellness Clinic Irvine", Computer_Name: "AnaHealthPC", Status: "Warning", Product_Version: "7.8.4.140", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "No" },
    { Customer_Name: "Tustin Care and Recovery", Computer_Name: "IrvWellnessPC", Status: "Failed", Product_Version: "8.0.0.162", Space_Used: "1TB", Backup_Type: "DISK IMAGE", Encrypted: "Yes" },
    { Customer_Name: "Advanced Rehab Center Tustin", Computer_Name: "FullPrimePC", Status: "Success", Product_Version: "8.1.1.170", Space_Used: "2TB", Backup_Type: "DISK IMAGE", Encrypted: "No" }
];

