const backupData = [
  {
    Status: "Success",
    Comments: "Backup successful",
    BackupDate: "2024-07-01",
    TakenBy: "John Doe",
    CustomerName: "Customer A",
    AssetName: "Server 1",
    AssetTag: "A001",
    ScheduleDate: "2024-06-30",
    BackupSchedule: "Daily",
    BackupType: "Full",
    BackupServer: "Server A",
    BackupSoftware: "BackupSoft v1.0",
  },
  {
    Status: "Failed",
    Comments: "Network error",
    BackupDate: "2024-07-02",
    TakenBy: "Jane Smith",
    CustomerName: "Customer B",
    AssetName: "Database 1",
    AssetTag: "B002",
    ScheduleDate: "2024-06-29",
    BackupSchedule: "Weekly",
    BackupType: "Incremental",
    BackupServer: "Server B",
    BackupSoftware: "BackupSoft v2.0",
  },
  {
    Status: "Warning",
    Comments: "Backup completed with warnings",
    BackupDate: "2024-07-03",
    TakenBy: "Alice Johnson",
    CustomerName: "Customer C",
    AssetName: "Web Server",
    AssetTag: "C003",
    ScheduleDate: "2024-06-28",
    BackupSchedule: "Monthly",
    BackupType: "Full",
    BackupServer: "Server C",
    BackupSoftware: "BackupSoft v1.5",
  },
  {
    Status: "Pending",
    Comments: "Scheduled for later",
    BackupDate: "2024-07-04",
    TakenBy: "Bob Brown",
    CustomerName: "Customer D",
    AssetName: "Mail Server",
    AssetTag: "D004",
    ScheduleDate: "2024-06-27",
    BackupSchedule: "Daily",
    BackupType: "Differential",
    BackupServer: "Server D",
    BackupSoftware: "BackupSoft v3.0",
  },
  {
    Status: "Success",
    Comments: "Backup successful",
    BackupDate: "2024-07-05",
    TakenBy: "Charlie White",
    CustomerName: "Customer E",
    AssetName: "File Server",
    AssetTag: "E005",
    ScheduleDate: "2024-06-26",
    BackupSchedule: "Weekly",
    BackupType: "Full",
    BackupServer: "Server E",
    BackupSoftware: "BackupSoft v2.5",
  },
  {
    Status: "Failed",
    Comments: "Disk space error",
    BackupDate: "2024-07-06",
    TakenBy: "David Green",
    CustomerName: "Customer F",
    AssetName: "Application Server",
    AssetTag: "F006",
    ScheduleDate: "2024-06-25",
    BackupSchedule: "Monthly",
    BackupType: "Incremental",
    BackupServer: "Server F",
    BackupSoftware: "BackupSoft v4.0",
  },
  {
    Status: "Success",
    Comments: "Backup successful",
    BackupDate: "2024-07-07",
    TakenBy: "Eve Black",
    CustomerName: "Customer G",
    AssetName: "Database 2",
    AssetTag: "G007",
    ScheduleDate: "2024-06-24",
    BackupSchedule: "Daily",
    BackupType: "Full",
    BackupServer: "Server G",
    BackupSoftware: "BackupSoft v1.0",
  },
  {
    Status: "Failed",
    Comments: "Authentication error",
    BackupDate: "2024-07-08",
    TakenBy: "Frank Blue",
    CustomerName: "Customer H",
    AssetName: "Server 2",
    AssetTag: "H008",
    ScheduleDate: "2024-06-23",
    BackupSchedule: "Weekly",
    BackupType: "Differential",
    BackupServer: "Server H",
    BackupSoftware: "BackupSoft v3.5",
  },
  {
    Status: "Success",
    Comments: "Backup completed successfully",
    BackupDate: "2024-07-09",
    TakenBy: "Grace Pink",
    CustomerName: "Customer I",
    AssetName: "Web Server 2",
    AssetTag: "I009",
    ScheduleDate: "2024-06-22",
    BackupSchedule: "Monthly",
    BackupType: "Full",
    BackupServer: "Server I",
    BackupSoftware: "BackupSoft v2.0",
  },
  {
    Status: "Pending",
    Comments: "Scheduled for next week",
    BackupDate: "2024-07-10",
    TakenBy: "Henry Purple",
    CustomerName: "Customer J",
    AssetName: "Mail Server 2",
    AssetTag: "J010",
    ScheduleDate: "2024-06-21",
    BackupSchedule: "Daily",
    BackupType: "Incremental",
    BackupServer: "Server J",
    BackupSoftware: "BackupSoft v3.0",
  },
];

export default backupData;
