npmScopes:
fortawesome:
  npmAlwaysAuth: true
  npmRegistryServer: "https://npm.fontawesome.com/"
  npmAuthToken: "E78CE3DF-7803-498D-8D7D-60FDAB1EC61E"
awesome.me:
  npmAlwaysAuth: true
  npmRegistryServer: "https://npm.fontawesome.com/"
  npmAuthToken: "E78CE3DF-7803-498D-8D7D-60FDAB1EC61E"
