export const contracts = [
  {
    Customer: "John Doe",
    Site: "Site A",
    Product: "Product 1",
    Description: "Maintenance and support services",
    StartDate: "2023-01-15",
    EndDate: "2024-01-14",
    TypeOfService: "Maintenance",
    ContractPricing: "$1,200",
    ContractType: "Annual",
  },
  {
    Customer: "Jane Smith",
    Site: "Site B",
    Product: "Product 2",
    Description: "Installation and setup",
    StartDate: "2023-03-01",
    EndDate: "2023-08-31",
    TypeOfService: "Installation",
    ContractPricing: "$3,500",
    ContractType: "One-time",
  },
  {
    Customer: "ACME Corp",
    Site: "Site C",
    Product: "Product 3",
    Description: "Comprehensive software support",
    StartDate: "2023-05-20",
    EndDate: "2025-05-19",
    TypeOfService: "Support",
    ContractPricing: "$5,000",
    ContractType: "Biennial",
  },
  {
    Customer: "XYZ Ltd",
    Site: "Site D",
    Product: "Product 4",
    Description: "Hardware and software maintenance",
    StartDate: "2022-10-10",
    EndDate: "2024-10-09",
    TypeOfService: "Maintenance",
    ContractPricing: "$2,500",
    ContractType: "Annual",
  },
  {
    Customer: "Global Tech",
    Site: "Site E",
    Product: "Product 5",
    Description: "On-demand IT services",
    StartDate: "2023-07-01",
    EndDate: "2023-12-31",
    TypeOfService: "Consulting",
    ContractPricing: "$1,800",
    ContractType: "Semi-annual",
  },
  {
    Customer: "Innovate LLC",
    Site: "Site F",
    Product: "Product 6",
    Description: "Custom software development",
    StartDate: "2023-06-15",
    EndDate: "2024-06-14",
    TypeOfService: "Development",
    ContractPricing: "$10,000",
    ContractType: "Annual",
  },
  {
    Customer: "Tech Solutions",
    Site: "Site G",
    Product: "Product 7",
    Description: "Cloud infrastructure setup",
    StartDate: "2023-04-01",
    EndDate: "2023-09-30",
    TypeOfService: "Setup",
    ContractPricing: "$4,200",
    ContractType: "One-time",
  },
  {
    Customer: "Future Enterprises",
    Site: "Site H",
    Product: "Product 8",
    Description: "Annual security audit",
    StartDate: "2023-09-01",
    EndDate: "2024-08-31",
    TypeOfService: "Audit",
    ContractPricing: "$3,000",
    ContractType: "Annual",
  },
  {
    Customer: "NextGen Innovations",
    Site: "Site I",
    Product: "Product 9",
    Description: "Remote IT support",
    StartDate: "2023-02-10",
    EndDate: "2023-08-09",
    TypeOfService: "Support",
    ContractPricing: "$2,000",
    ContractType: "Semi-annual",
  },
  {
    Customer: "Alpha Inc",
    Site: "Site J",
    Product: "Product 10",
    Description: "Network optimization services",
    StartDate: "2023-08-15",
    EndDate: "2024-02-14",
    TypeOfService: "Optimization",
    ContractPricing: "$2,500",
    ContractType: "Semi-annual",
  },
];
