const leaveData = [
  {
    displayName: "John Doe",
    startDate: "2023-01-01",
    endDate: "2023-01-02",
    leaveType: "Personal",
    status: "Approved",
    reason: "Family event",
  },
  {
    displayName: "Jane Smith",
    startDate: "2023-02-10",
    endDate: "2023-02-12",
    leaveType: "Sick",
    status: "Approved",
    reason: "Flu",
  },
  {
    displayName: "Alice Johnson",
    startDate: "2023-03-15",
    endDate: "2023-03-16",
    leaveType: "Compensatory",
    status: "Rejected",
    reason: "Workload",
  },
  {
    displayName: "Bob Brown",
    startDate: "2023-04-05",
    endDate: "2023-04-06",
    leaveType: "Personal",
    status: "Approved",
    reason: "Vacation",
  },
  {
    displayName: "Charlie Davis",
    startDate: "2023-05-10",
    endDate: "2023-05-12",
    leaveType: "Sick",
    status: "Rejected",
    reason: "Not specified",
  },
  {
    displayName: "Debbie White",
    startDate: "2023-06-20",
    endDate: "2023-06-21",
    leaveType: "Compensatory",
    status: "Approved",
    reason: "Extra hours",
  },
  {
    displayName: "Ethan Black",
    startDate: "2023-07-07",
    endDate: "2023-07-08",
    leaveType: "Personal",
    status: "Approved",
    reason: "Travel",
  },
  {
    displayName: "Fiona Green",
    startDate: "2023-08-18",
    endDate: "2023-08-20",
    leaveType: "Sick",
    status: "Approved",
    reason: "Medical procedure",
  },
  {
    displayName: "George Adams",
    startDate: "2023-09-25",
    endDate: "2023-09-26",
    leaveType: "Compensatory",
    status: "Rejected",
    reason: "Project deadline",
  },
  {
    displayName: "Hannah Wilson",
    startDate: "2023-10-03",
    endDate: "2023-10-04",
    leaveType: "Personal",
    status: "Approved",
    reason: "Wedding",
  },
  {
    displayName: "Ian Clark",
    startDate: "2023-11-11",
    endDate: "2023-11-12",
    leaveType: "Sick",
    status: "Rejected",
    reason: "Insufficient proof",
  },
  {
    displayName: "Jill Martinez",
    startDate: "2023-12-24",
    endDate: "2023-12-26",
    leaveType: "Compensatory",
    status: "Approved",
    reason: "Holiday work",
  },
  {
    displayName: "Kevin Moore",
    startDate: "2023-01-15",
    endDate: "2023-01-17",
    leaveType: "Personal",
    status: "Rejected",
    reason: "Work requirement",
  },
  {
    displayName: "Laura Taylor",
    startDate: "2023-02-21",
    endDate: "2023-02-22",
    leaveType: "Sick",
    status: "Approved",
    reason: "Migraine",
  },
  {
    displayName: "Mike Anderson",
    startDate: "2023-03-08",
    endDate: "2023-03-09",
    leaveType: "Compensatory",
    status: "Rejected",
    reason: "Not eligible",
  },
  {
    displayName: "Nina Thomas",
    startDate: "2023-04-12",
    endDate: "2023-04-13",
    leaveType: "Personal",
    status: "Approved",
    reason: "Anniversary",
  },
  {
    displayName: "Oliver Harris",
    startDate: "2023-05-19",
    endDate: "2023-05-20",
    leaveType: "Sick",
    status: "Rejected",
    reason: "Insufficient proof",
  },
  {
    displayName: "Paula Lewis",
    startDate: "2023-06-23",
    endDate: "2023-06-25",
    leaveType: "Compensatory",
    status: "Approved",
    reason: "Extra hours",
  },
  {
    displayName: "Quincy Walker",
    startDate: "2023-07-14",
    endDate: "2023-07-15",
    leaveType: "Personal",
    status: "Approved",
    reason: "Family event",
  },
  {
    displayName: "Rachel Hall",
    startDate: "2023-08-29",
    endDate: "2023-08-30",
    leaveType: "Sick",
    status: "Approved",
    reason: "Cold",
  },
  {
    displayName: "Sam Young",
    startDate: "2023-09-04",
    endDate: "2023-09-05",
    leaveType: "Compensatory",
    status: "Rejected",
    reason: "Not eligible",
  },
  {
    displayName: "Tina King",
    startDate: "2023-10-09",
    endDate: "2023-10-10",
    leaveType: "Personal",
    status: "Approved",
    reason: "Vacation",
  },
  {
    displayName: "Uma Scott",
    startDate: "2023-11-16",
    endDate: "2023-11-17",
    leaveType: "Sick",
    status: "Rejected",
    reason: "Not specified",
  },
  {
    displayName: "Victor Harris",
    startDate: "2023-12-01",
    endDate: "2023-12-02",
    leaveType: "Compensatory",
    status: "Approved",
    reason: "Extra hours",
  },
  {
    displayName: "Wendy Robinson",
    startDate: "2023-01-20",
    endDate: "2023-01-22",
    leaveType: "Personal",
    status: "Approved",
    reason: "Travel",
  },
  {
    displayName: "Xavier Brown",
    startDate: "2023-02-13",
    endDate: "2023-02-14",
    leaveType: "Sick",
    status: "Approved",
    reason: "Medical appointment",
  },
  {
    displayName: "Yara Carter",
    startDate: "2023-03-07",
    endDate: "2023-03-08",
    leaveType: "Compensatory",
    status: "Rejected",
    reason: "Not eligible",
  },
  {
    displayName: "Zachary Allen",
    startDate: "2023-04-15",
    endDate: "2023-04-16",
    leaveType: "Personal",
    status: "Approved",
    reason: "Family event",
  },
  {
    displayName: "Amber Mitchell",
    startDate: "2023-05-28",
    endDate: "2023-05-30",
    leaveType: "Sick",
    status: "Rejected",
    reason: "Insufficient proof",
  },
  {
    displayName: "Blake Evans",
    startDate: "2023-06-10",
    endDate: "2023-06-11",
    leaveType: "Compensatory",
    status: "Approved",
    reason: "Extra hours",
  },
];

export default leaveData;
