export const Tickets = [
  {
    Incident: "INC48831",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "10 Open",
    Severity: "Non Critical Issue",
    Subject: "Scan Documents to Email",
    Assignee: "Abhishek Jadhav",
    Contact_Name: "Vikas",
    Contact_Email: "abhishek@ashunya.com",
    Date_Closed: "03-JUL-2024",
    Product_Version: "",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 09:40PM",
    Updated: "2024 10:27PM",
  },
  {
    Incident: "INC48832",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "10 Open",
    Severity: "Critical Issue",
    Subject: "System Crash",
    Assignee: "Priya Kumar",
    Contact_Name: "Rohan",
    Contact_Email: "priya@ashunya.com",
    Date_Closed: "04-JUL-2024",
    Product_Version: "2.3",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 10:10PM",
    Updated: "2024 10:30PM",
  },
  {
    Incident: "INC48833",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "20 In Progress",
    Severity: "Moderate Issue",
    Subject: "Connectivity Problems",
    Assignee: "Rahul Verma",
    Contact_Name: "Anita",
    Contact_Email: "rahul@ashunya.com",
    Date_Closed: "",
    Product_Version: "",
    Status_Code: "20",
    Status_Name: "In Progress",
    Closing_Remark: "",
    Created: "2024 09:50PM",
    Updated: "2024 10:40PM",
  },
  {
    Incident: "INC48834",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "30 Resolved",
    Severity: "High Issue",
    Subject: "Printer Malfunction",
    Assignee: "Sneha Patil",
    Contact_Name: "Manoj",
    Contact_Email: "sneha@ashunya.com",
    Date_Closed: "05-JUL-2024",
    Product_Version: "1.1",
    Status_Code: "30",
    Status_Name: "Resolved",
    Closing_Remark: "Printer replaced",
    Created: "2024 11:00PM",
    Updated: "2024 11:20PM",
  },
  {
    Incident: "INC48835",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "10 Open",
    Severity: "Low Issue",
    Subject: "Login Issue",
    Assignee: "Vikram Singh",
    Contact_Name: "Preeti",
    Contact_Email: "vikram@ashunya.com",
    Date_Closed: "",
    Product_Version: "3.0",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 09:20PM",
    Updated: "2024 09:45PM",
  },
  {
    Incident: "INC48836",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "40 Closed",
    Severity: "Critical Issue",
    Subject: "Server Downtime",
    Assignee: "Ravi Kapoor",
    Contact_Name: "Karan",
    Contact_Email: "ravi@ashunya.com",
    Date_Closed: "06-JUL-2024",
    Product_Version: "",
    Status_Code: "40",
    Status_Name: "Closed",
    Closing_Remark: "Issue resolved",
    Created: "2024 10:15PM",
    Updated: "2024 11:00PM",
  },
  {
    Incident: "INC48837",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "10 Open",
    Severity: "Non Critical Issue",
    Subject: "Keyboard Replacement",
    Assignee: "Nisha Sharma",
    Contact_Name: "Deepak",
    Contact_Email: "nisha@ashunya.com",
    Date_Closed: "",
    Product_Version: "",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 08:40PM",
    Updated: "2024 09:20PM",
  },
  {
    Incident: "INC48838",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "20 In Progress",
    Severity: "High Issue",
    Subject: "Bug in Application",
    Assignee: "Suresh Nair",
    Contact_Name: "Amit",
    Contact_Email: "suresh@ashunya.com",
    Date_Closed: "",
    Product_Version: "1.2",
    Status_Code: "20",
    Status_Name: "In Progress",
    Closing_Remark: "",
    Created: "2024 09:35PM",
    Updated: "2024 10:50PM",
  },
  {
    Incident: "INC48839",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "30 Resolved",
    Severity: "Moderate Issue",
    Subject: "VPN Issues",
    Assignee: "Kiran Desai",
    Contact_Name: "Nitin",
    Contact_Email: "kiran@ashunya.com",
    Date_Closed: "07-JUL-2024",
    Product_Version: "",
    Status_Code: "30",
    Status_Name: "Resolved",
    Closing_Remark: "VPN configuration updated",
    Created: "2024 10:05PM",
    Updated: "2024 10:45PM",
  },
  {
    Incident: "INC48840",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "10 Open",
    Severity: "Low Issue",
    Subject: "Monitor Flickering",
    Assignee: "Anjali Mehta",
    Contact_Name: "Rashmi",
    Contact_Email: "anjali@ashunya.com",
    Date_Closed: "",
    Product_Version: "2.1",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 08:50PM",
    Updated: "2024 09:30PM",
  },
  {
    Incident: "INC48841",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "20 In Progress",
    Severity: "Critical Issue",
    Subject: "Database Corruption",
    Assignee: "Neha Reddy",
    Contact_Name: "Sunil",
    Contact_Email: "neha@ashunya.com",
    Date_Closed: "",
    Product_Version: "3.1",
    Status_Code: "20",
    Status_Name: "In Progress",
    Closing_Remark: "",
    Created: "2024 09:15PM",
    Updated: "2024 10:35PM",
  },
  {
    Incident: "INC48842",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "30 Resolved",
    Severity: "Non Critical Issue",
    Subject: "Slow Internet",
    Assignee: "Ankit Joshi",
    Contact_Name: "Suresh",
    Contact_Email: "ankit@ashunya.com",
    Date_Closed: "08-JUL-2024",
    Product_Version: "",
    Status_Code: "30",
    Status_Name: "Resolved",
    Closing_Remark: "Internet speed optimized",
    Created: "2024 10:25PM",
    Updated: "2024 10:55PM",
  },
  {
    Incident: "INC48843",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "40 Closed",
    Severity: "Moderate Issue",
    Subject: "Hard Drive Failure",
    Assignee: "Rita Shah",
    Contact_Name: "Rajesh",
    Contact_Email: "rita@ashunya.com",
    Date_Closed: "09-JUL-2024",
    Product_Version: "",
    Status_Code: "40",
    Status_Name: "Closed",
    Closing_Remark: "Hard drive replaced",
    Created: "2024 08:45PM",
    Updated: "2024 09:25PM",
  },
  {
    Incident: "INC48844",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "10 Open",
    Severity: "High Issue",
    Subject: "License Expired",
    Assignee: "Ajay Gupta",
    Contact_Name: "Neeraj",
    Contact_Email: "ajay@ashunya.com",
    Date_Closed: "",
    Product_Version: "2.5",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 09:55PM",
    Updated: "2024 10:20PM",
  },
  {
    Incident: "INC48845",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "20 In Progress",
    Severity: "Low Issue",
    Subject: "Firewall Configuration",
    Assignee: "Rakesh Singh",
    Contact_Name: "Jatin",
    Contact_Email: "rakesh@ashunya.com",
    Date_Closed: "",
    Product_Version: "",
    Status_Code: "20",
    Status_Name: "In Progress",
    Closing_Remark: "",
    Created: "2024 10:35PM",
    Updated: "2024 10:50PM",
  },
  {
    Incident: "INC48846",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "30 Resolved",
    Severity: "Moderate Issue",
    Subject: "RAM Upgrade",
    Assignee: "Priya Jain",
    Contact_Name: "Vinay",
    Contact_Email: "priya@ashunya.com",
    Date_Closed: "10-JUL-2024",
    Product_Version: "1.0",
    Status_Code: "30",
    Status_Name: "Resolved",
    Closing_Remark: "RAM upgraded",
    Created: "2024 09:25PM",
    Updated: "2024 09:55PM",
  },
  {
    Incident: "INC48847",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "40 Closed",
    Severity: "Critical Issue",
    Subject: "Security Breach",
    Assignee: "Rohit Malhotra",
    Contact_Name: "Arun",
    Contact_Email: "rohit@ashunya.com",
    Date_Closed: "11-JUL-2024",
    Product_Version: "3.2",
    Status_Code: "40",
    Status_Name: "Closed",
    Closing_Remark: "Security measures enhanced",
    Created: "2024 09:45PM",
    Updated: "2024 10:10PM",
  },
  {
    Incident: "INC48848",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "10 Open",
    Severity: "Non Critical Issue",
    Subject: "Router Configuration",
    Assignee: "Geeta Deshpande",
    Contact_Name: "Sanjay",
    Contact_Email: "geeta@ashunya.com",
    Date_Closed: "",
    Product_Version: "",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 09:35PM",
    Updated: "2024 10:25PM",
  },
  {
    Incident: "INC48849",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "20 In Progress",
    Severity: "Low Issue",
    Subject: "Mouse Not Working",
    Assignee: "Meera Kapoor",
    Contact_Name: "Sandeep",
    Contact_Email: "meera@ashunya.com",
    Date_Closed: "",
    Product_Version: "",
    Status_Code: "20",
    Status_Name: "In Progress",
    Closing_Remark: "",
    Created: "2024 08:55PM",
    Updated: "2024 09:40PM",
  },
  {
    Incident: "INC48850",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "30 Resolved",
    Severity: "Moderate Issue",
    Subject: "Software Installation",
    Assignee: "Anil Kumar",
    Contact_Name: "Dinesh",
    Contact_Email: "anil@ashunya.com",
    Date_Closed: "12-JUL-2024",
    Product_Version: "1.3",
    Status_Code: "30",
    Status_Name: "Resolved",
    Closing_Remark: "Software installed successfully",
    Created: "2024 09:50PM",
    Updated: "2024 10:30PM",
  },
  {
    Incident: "INC48851",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "40 Closed",
    Severity: "High Issue",
    Subject: "Network Outage",
    Assignee: "Vivek Patel",
    Contact_Name: "Gaurav",
    Contact_Email: "vivek@ashunya.com",
    Date_Closed: "13-JUL-2024",
    Product_Version: "",
    Status_Code: "40",
    Status_Name: "Closed",
    Closing_Remark: "Network restored",
    Created: "2024 10:00PM",
    Updated: "2024 10:45PM",
  },
  {
    Incident: "INC48852",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Hardware",
    Status: "10 Open",
    Severity: "Critical Issue",
    Subject: "Power Supply Failure",
    Assignee: "Alok Mishra",
    Contact_Name: "Vivek",
    Contact_Email: "alok@ashunya.com",
    Date_Closed: "",
    Product_Version: "",
    Status_Code: "10",
    Status_Name: "Open",
    Closing_Remark: "",
    Created: "2024 09:10PM",
    Updated: "2024 10:20PM",
  },
  {
    Incident: "INC48853",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Software",
    Status: "20 In Progress",
    Severity: "Non Critical Issue",
    Subject: "User Permissions",
    Assignee: "Kavita Sharma",
    Contact_Name: "Kailash",
    Contact_Email: "kavita@ashunya.com",
    Date_Closed: "",
    Product_Version: "2.0",
    Status_Code: "20",
    Status_Name: "In Progress",
    Closing_Remark: "",
    Created: "2024 08:30PM",
    Updated: "2024 09:50PM",
  },
  {
    Incident: "INC48854",
    Customer: "Ashunya Support",
    Site_Name: "ashunya.com",
    Product: "Network",
    Status: "30 Resolved",
    Severity: "Moderate Issue",
    Subject: "IP Conflict",
    Assignee: "Rohan Gupta",
    Contact_Name: "Tarun",
    Contact_Email: "rohan@ashunya.com",
    Date_Closed: "14-JUL-2024",
    Product_Version: "",
    Status_Code: "30",
    Status_Name: "Resolved",
    Closing_Remark: "IP conflict resolved",
    Created: "2024 09:30PM",
    Updated: "2024 10:00PM",
  },
];
