export const data = [
  {
    Username: "Aarav Singh",
    Email: "aarav.singh@example.com",
    OpenTickets: 5,
    ClosedTickets: 10,
    LastClosed: "2 days ago",
  },
  {
    Username: "Vihaan Sharma",
    Email: "vihaan.sharma@example.com",
    OpenTickets: 3,
    ClosedTickets: 7,
    LastClosed: "2 days ago",
  },
  {
    Username: "Vivaan Patel",
    Email: "vivaan.patel@example.com",
    OpenTickets: 2,
    ClosedTickets: 8,
    LastClosed: "2 days ago",
  },
  {
    Username: "Aditya Mehta",
    Email: "aditya.mehta@example.com",
    OpenTickets: 4,
    ClosedTickets: 12,
    LastClosed: "2 days ago",
  },
  {
    Username: "Arjun Rao",
    Email: "arjun.rao@example.com",
    OpenTickets: 6,
    ClosedTickets: 9,
    LastClosed: "2 days ago",
  },
  {
    Username: "Sai Iyer",
    Email: "sai.iyer@example.com",
    OpenTickets: 7,
    ClosedTickets: 5,
    LastClosed: "2 days ago",
  },
  {
    Username: "Reyansh Gupta",
    Email: "reyansh.gupta@example.com",
    OpenTickets: 4,
    ClosedTickets: 11,
    LastClosed: "2 days ago",
  },
  {
    Username: "Krishna Nair",
    Email: "krishna.nair@example.com",
    OpenTickets: 5,
    ClosedTickets: 6,
    LastClosed: "2 days ago",
  },
  {
    Username: "Ishaan Joshi",
    Email: "ishaan.joshi@example.com",
    OpenTickets: 6,
    ClosedTickets: 9,
    LastClosed: "2 days ago",
  },
  {
    Username: "Shaurya Reddy",
    Email: "shaurya.reddy@example.com",
    OpenTickets: 3,
    ClosedTickets: 10,
    LastClosed: "2 days ago",
  },
  {
    Username: "Ayaan Jain",
    Email: "ayaan.jain@example.com",
    OpenTickets: 8,
    ClosedTickets: 2,
    LastClosed: "2 days ago",
  },
  {
    Username: "Kabir Khan",
    Email: "kabir.khan@example.com",
    OpenTickets: 7,
    ClosedTickets: 6,
    LastClosed: "2 days ago",
  },
  {
    Username: "Atharv Aggarwal",
    Email: "atharv.aggarwal@example.com",
    OpenTickets: 5,
    ClosedTickets: 7,
    LastClosed: "2 days ago",
  },
  {
    Username: "Ansh Mishra",
    Email: "ansh.mishra@example.com",
    OpenTickets: 4,
    ClosedTickets: 8,
    LastClosed: "2 days ago",
  },
  {
    Username: "Dhruv Bhat",
    Email: "dhruv.bhat@example.com",
    OpenTickets: 9,
    ClosedTickets: 3,
    LastClosed: "2 days ago",
  },
  {
    Username: "Aarush Desai",
    Email: "aarush.desai@example.com",
    OpenTickets: 6,
    ClosedTickets: 7,
    LastClosed: "2 days ago",
  },
  {
    Username: "Om Singh",
    Email: "om.singh@example.com",
    OpenTickets: 5,
    ClosedTickets: 9,
    LastClosed: "2 days ago",
  },
  {
    Username: "Parth Sharma",
    Email: "parth.sharma@example.com",
    OpenTickets: 4,
    ClosedTickets: 10,
    LastClosed: "2 days ago",
  },
  {
    Username: "Arnav Reddy",
    Email: "arnav.reddy@example.com",
    OpenTickets: 3,
    ClosedTickets: 11,
    LastClosed: "2 days ago",
  },
  {
    Username: "Atharva Gupta",
    Email: "atharva.gupta@example.com",
    OpenTickets: 7,
    ClosedTickets: 4,
    LastClosed: "2 days ago",
  },
  {
    Username: "Harsh Mehta",
    Email: "harsh.mehta@example.com",
    OpenTickets: 6,
    ClosedTickets: 5,
    LastClosed: "2 days ago",
  },
  {
    Username: "Yuvaan Patel",
    Email: "yuvaan.patel@example.com",
    OpenTickets: 5,
    ClosedTickets: 6,
    LastClosed: "2 days ago",
  },
  {
    Username: "Rudra Iyer",
    Email: "rudra.iyer@example.com",
    OpenTickets: 4,
    ClosedTickets: 9,
    LastClosed: "2 days ago",
  },
  {
    Username: "Aryan Nair",
    Email: "aryan.nair@example.com",
    OpenTickets: 8,
    ClosedTickets: 3,
    LastClosed: "2 days ago",
  },
  {
    Username: "Advait Joshi",
    Email: "advait.joshi@example.com",
    OpenTickets: 3,
    ClosedTickets: 12,
    LastClosed: "2 days ago",
  },
  {
    Username: "Dev Bhat",
    Email: "dev.bhat@example.com",
    OpenTickets: 7,
    ClosedTickets: 5,
    LastClosed: "2 days ago",
  },
  {
    Username: "Rohan Desai",
    Email: "rohan.desai@example.com",
    OpenTickets: 6,
    ClosedTickets: 8,
    LastClosed: "2 days ago",
  },
  {
    Username: "Pranav Singh",
    Email: "pranav.singh@example.com",
    OpenTickets: 5,
    ClosedTickets: 7,
    LastClosed: "2 days ago",
  },
  {
    Username: "Ritvik Sharma",
    Email: "ritvik.sharma@example.com",
    OpenTickets: 4,
    ClosedTickets: 9,
    LastClosed: "2 days ago",
  },
  {
    Username: "Samarth Reddy",
    Email: "samarth.reddy@example.com",
    OpenTickets: 3,
    ClosedTickets: 10,
    LastClosed: "2 days ago",
  },
];
